name: diverse_psro
channels:
  - conda-forge
  - defaults
dependencies:
  - certifi=2020.12.5
  - pip=21.0.1=pyhd8ed1ab_0
  - python=3.6.12
  - python_abi=3.6=1_cp36m
  - setuptools=49.6.0
  - wheel=0.36.2=pyhd3deb0d_0
  - pip:
    - absl-py==0.11.0
    - cycler==0.10.0
    - dataclasses==0.8
    - joblib==1.0.1
    - kiwisolver==1.3.1
    - matplotlib==3.3.4
    - numpy==1.19.5
    - pillow==8.1.0
    - pyparsing==2.4.7
    - python-dateutil==2.8.1
    - scikit-learn==0.24.1
    - scipy==1.5.4
    - six==1.15.0
    - sklearn==0.0
    - threadpoolctl==2.1.0
    - torch==1.7.1
    - typing-extensions==3.7.4.3
